# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  test:
    docker:
      - image: circleci/python:3.7.2

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --cov-report term --cov=./tests/

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - codecov/upload:
          file: .coverage

  deploy:
    machine: true

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: deploy to heroku
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
            docker build --rm=false -t registry.heroku.com/prograce/web .
            docker push registry.heroku.com/prograce/web:latest

workflows:
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
